<Project>
    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
        <AnalysisLevel>latest</AnalysisLevel>
        <LangVersion>Latest</LangVersion>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <NoWarn>$(NoWarn),AV2210</NoWarn>
    </PropertyGroup>
</Project>